### PR TITLE
added last pressed to state

### PR DESCRIPTION
**Pull request by louiidev**

### CODE REVIEW

**Review by denvaar — COMMENTED** [review]
Hi @louisgjohnson thanks for the PR. I like this solution, but I have a question. the game loop function is called recursively, so the keypress handler will now be registered on each recursive call. What's the impact of this?

**Comment by denvaar** [comment]
Also, can you please reference the issue in your pull request.

**Comment by louisgjohnson** [comment]
> Hi @louisgjohnson thanks for the PR. I like this solution, but I have a question. the game loop function is called recursively, so the keypress handler will now be registered on each recursive call. What's the impact of this?

updated my logic, ended up putting the game loop into a class to prevent the listener being recalled every loop

**Comment by louisgjohnson** [comment]
> Also, can you please reference the issue in your pull request.

How do i do that?

**Comment by denvaar** [comment]
> How do i do that?

Just type a pound sign and then you can select the issue. Like this: #7

**Comment by denvaar** [comment]
Now that I merged the other pull requests, this has a conflict. Can you please resolve? I will merge this, but I am not super fond of using a class for this. I think an easier way could be a closure. I will still merge, but will probably keep the issue open to use a closure instead. This does make lastPressed not global anymore, so thanks :)

**Comment by louisgjohnson** [comment]
> Now that I merged the other pull requests, this has a conflict. Can you please resolve? I will merge this, but I am not super fond of using a class for this. I think an easier way could be a closure. I will still merge, but will probably keep the issue open to use a closure instead. This does make lastPressed not global anymore, so thanks :)

Yeah a closure isn't a bad idea, I'll keep playing around with it

**Pull request closed without merging**
