### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by davidlaym**
#4 
- [x] Add jest as unit test framework
- [x] Add some package.json scripts for tests
- [x] Update Readme for the new package.json scripts
- [x] Coverage for `drawGame`
- [x] Coverage for `processInputs`
- [x] Coverage for `processPosition`
- [x] Coverage for `utils`

Can't really commit to coverage for app.ts. In order to make it testeable, the game loop and the keypress handler could be extracted.

### CODE REVIEW

**Comment by denvaar** [comment]
Thanks, let me know when you're ready for review

**Comment by davidlaym** [comment]
@denvaar ready for review :)

**Comment by denvaar** [comment]
Thanks @davidlaym . Please resolve conflicts and I will merge

**Comment by davidlaym** [comment]
@denvaar merge ready

**Pull request closed without merging**
